import 'package:ai_cricket_coach/core/resources/data_state.dart';
import 'package:ai_cricket_coach/features/sessions/data/repositories/session_repository_impl.dart';
import 'package:ai_cricket_coach/features/sessions/domain/entities/session.dart';
import 'package:firebase_core/firebase_core.dart';
import 'features/sessions/data/repositories/session_repository_impl.dart';
import 'features/sessions/domain/entities/session.dart';

Future<void> main() async {
  // Initialize Firebase
  await Firebase.initializeApp();

  // Create an instance of your repository implementation
  final sessionRepository = SessionRepositoryImpl();

  // Test: Create an empty session
  final emptySession = SessionEntity(
    id: '', // ID will be auto-generated by Firestore
    dateTime: DateTime.now(), // Current date-time
    deliveryCount: 0, // No deliveries initially
    averageExecutionRating: 0.0, // No rating initially
    averageSpeed: 0.0, // No speed initially
    averageAccuracy: 0.0, // No accuracy initially
  );

  // Call the createSession method
  final response = await sessionRepository.createSession(emptySession);

  if (response is DataSuccess) {
    // Access the session ID from the success response
    final sessionId = response.data; // Ensure this matches your createSession return type
    print('Session created successfully with ID: $sessionId');
  } else if (response is DataFailed) {
    // Access the error message
    final error = response.error;
    print('Failed to create session: ${error?.message}');
  }
}
