name: ai_cricket_coach
description: "AI Cricket Coach Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.2.2


  cupertino_icons: ^1.0.8

  # State management
  flutter_bloc: ^8.1.6

  # Comparing dart objects
  equatable: ^2.0.7

  # Service locator
  get_it: ^8.0.2

  # Date formatting
  intl: ^0.20.1

  # Database
  floor: ^1.5.0

  # Make request to API
  retrofit: ^4.4.1

  # Hooks
  flutter_hooks: ^0.20.5

  # Cached image
  cached_network_image: ^3.4.1

  # Dio
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Updated Flutter lints
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
