/// Maps ideal shot names to their respective image asset paths.
const Map<String, String> shotImages = {
  "Pull Shot": "assets/images/pull_shot.png",
  "Sweep": "assets/images/sweep.png",
  "Leg Glance": "assets/images/leg_glance.png",
  "Slog": "assets/images/slog.png",
  "Drive Straight": "assets/images/drive_straight.png",
  "Block Shot Forward": "assets/images/block_shot_forward.png",
  "Back-Foot Drive": "assets/images/back_foot_drive.png",
  "Upper Cut": "assets/images/upper_cut.png",
  "Hook Shot": "assets/images/hook_shot.png",
  "Late Cut": "assets/images/late_cut.png",
  "Straight Drive": "assets/images/straight_drive.png",
  "Lofted Drive Off": "assets/images/lofted_drive_off.png",
  "Drive Off": "assets/images/drive_off.png",
  "Lofted Off Drive": "assets/images/lofted_off_drive.png",
  "Lofted Drive On": "assets/images/lofted_drive_on.png",
  "Square Cut": "assets/images/square_cut.png",
  "Back-Foot Leg Glance": "assets/images/back_foot_leg_glance.png",
  "Drive Cover": "assets/images/drive_cover.png",
  "cut": "assets/images/cut.gif",
  "Reverse Sweep": "assets/images/reverse_sweep.png",
  "Lofted On Drive": "assets/images/lofted_on_drive.png",
  "Drive On": "assets/images/drive_on.png",
  "Lofted Straight Drive": "assets/images/lofted_straight_drive.png",
};

/// Maps ideal shot names to their respective instructions.
const Map<String, String> shotInstructions = {
  "Pull Shot": "Shift your weight onto your back foot, pivot your body, and swing horizontally to hit the ball square or behind square on the leg side.",
  "Sweep": "Kneel on your back knee, position your bat low, and sweep horizontally to strike the ball toward the leg side.",
  "Leg Glance": "Use soft hands and a delicate flick to guide the ball off your pads toward fine leg or square leg.",
  "Slog": "Swing the bat aggressively with a strong bottom hand to loft the ball over the fielders in the leg side.",
  "Drive Straight": "Step forward with your front foot, keep the bat straight, and punch the ball along the ground.",
  "Block Shot Forward": "Defensively meet the ball with a firm, straight bat, ensuring the ball stays close to the ground.",
  "Back-Foot Drive": "Step back, create space, and drive the ball through the off side with a straight bat.",
  "Upper Cut": "Use a square stance, wait for a short ball, and guide it over the slip cordon.",
  "Hook Shot": "Pull the bat over your shoulder to strike a high bouncer, aiming for the leg side boundary.",
  "Late Cut": "Let the ball pass slightly and use soft hands to steer it behind square on the off side.",
  "Straight Drive": "Lean forward with a straight bat to drive the ball straight past the bowler.",
  "Lofted Drive Off": "Swing the bat upward to loft the ball over the off side field.",
  "Drive Off": "Use a straight bat to push the ball through the off side along the ground.",
  "Lofted Off Drive": "Combine footwork and timing to loft the ball over the off side field.",
  "Lofted Drive On": "Drive the ball upward over the on side with strong bottom-hand control.",
  "Square Cut": "Step back and cut the ball with a horizontal bat through the square on the off side.",
  "Back-Foot Leg Glance": "Play softly off the back foot to guide the ball toward the leg side.",
  "Drive Cover": "Lean forward and drive the ball through the covers with elegant footwork.",
  "cut": "This shot involves hitting the ball hard and across the line of the ball, using a horizontal bat and an angled follow-through. To improve your cut shots, practice getting your feet into position and using a clean, crisp action.",
  "Reverse Sweep": "Switch the bat's direction and sweep the ball toward the off side.",
  "Lofted On Drive": "Step forward and loft the ball toward the on side boundary.",
  "Drive On": "Use a straight bat to push the ball along the ground through the on side.",
  "Lofted Straight Drive": "Lean forward and loft the ball straight past the bowler toward the boundary.",
};