# openapi2-run.yaml
swagger: '2.0'
info:
  title: AICC API
  description: API Gateway with a Cloud Run backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://my-app-image-174827312206.us-central1.run.app/
paths:
  /signup:
    post:
      summary: Register a new user
      operationId: signUpUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                  description: Email address of the user.
                password:
                  type: string
                  format: password
                  description: Password for the user.
              required:
                - email
                - password
      responses:
        '200':
          description: User registration was successful.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  uid:
                    type: string
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
    /login:
      post:
        summary: Log in an existing user
        operationId: logInUser
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
                    format: password
                    description: Firebase ID token for authentication.
                required:
                  - password
        responses:
          '200':
            description: User logged in successfully.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
                    uid:
                      type: string
                    email:
                      type: string
          '404':
            description: User not found.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string
          '500':
            description: Internal server error.
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    status:
                      type: string
                    message:
                      type: string